name: AutoTorch
version: '1.0.0'
main: gg.kite.core.Main
api-version: '1.21'
authors: [ KiteGG ]
website: https://ks.akii.pro
description: Automatically places torches when light levels are low.
commands:
  autotorch:
    description: Manage the AutoTorch plugin.
    usage: /autotorch [reload|toggle]
permissions:
  autotorch.use:
    description: Allows players to use the AutoTorch feature.
    default: true
  autotorch.toggle:
    description: Allows players to toggle AutoTorch on/off.
    default: true
  autotorch.admin.reload:
    description: Allows admins to reload the plugin configuration.
    default: op